### ISSUE TITLE
Release v0.1.1

### ISSUE THREAD

**Issue by blake-regalia** [Open-MBEE/flexo-mms-deployment#4]
- [x] https://github.com/Open-MBEE/mms5-layer1-service/issues/84
- [x] #3 
- [x] https://github.com/Open-MBEE/mms5-layer1-service/issues/88
- [x] https://github.com/Open-MBEE/mms5-layer1-service/issues/72
